spring:
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/rest_with_springboot_training?useTimezone=true&serverTimezone=UTC
      username: root
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.dialect.hibernate.MySQL8Dialect
      show-sql: false